# .github/workflows/mern.yml

name: MERN Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download files project
        uses: actions/checkout@v3

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install server packages
        working-directory: ./server
        run: npm install

      - name: install interface packages
        working-directory: ./client
        run: npm install

      - name: Build react app
        working-directory: ./client
        run: npm run build